# Generated by Django 3.0.3 on 2023-05-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_host_id_alter_operativesystemmatch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('countryCode', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('regionName', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('timezone', models.CharField(max_length=100)),
                ('isp', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('as_name', models.CharField(max_length=100)),
                ('reverse', models.CharField(max_length=100)),
                ('mobile', models.BooleanField()),
                ('proxy', models.BooleanField()),
                ('hosting', models.BooleanField()),
                ('query', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='host',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operativesystemmatch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='port',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scannerhistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='whois',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
