# Generated by Django 3.0.3 on 2023-05-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20230510_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipdata',
            name='query',
        ),
    ]
