# Generated by Django 3.0.3 on 2023-05-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_ipdata_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipdata',
            name='reverse',
        ),
    ]
