# Generated by Django 3.0.3 on 2023-05-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_ipdata_reverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdata',
            name='hosting',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='mobile',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='proxy',
            field=models.BooleanField(null=True),
        ),
    ]
